name: 'ce-boostup-xii'

services:
  sveltekit:
    build: .
    container_name: ce-boostup-xii-sveltekit
    ports:
      - '5173:5173'
    healthcheck:
      test: 'curl -I http://localhost:5173 || exit 1'
      start_period: 10s
      start_interval: 1s
    restart: unless-stopped
